### ISSUE TITLE
Roadmap of 2021

### ISSUE THREAD

**Issue by ije** [esm-dev/esm.sh#99]
### Roadmap List
- [x] split internal bundle by the `exports` field in **package.json** (#78)
- [x] support storage interface to save builds to everywhere over local fs(#76)
- [x] nested deps should respect the `?deps` parameter(#101)
- [ ] use deno deploy as front layer 
- [ ] preload deps 
- [ ] transform ts/tsx/jsx for browsers from **github**
  ```js
  import "https://esm.sh/~ije/ui/Button.tsx"  // Content-Type: application/javascript
  ```

**Comment by jimisaacs** [comment]
@ije I have a local branch where I have basically taken an additive approach to the fs_local implementation (duplicated and layer onto fs_local), and added https://github.com/dgraph-io/ristretto as a gate keeper. Would you be interested?

**Comment by jimisaacs** [comment]
Take a look at that project if you can, it's an interesting approach:
> High Hit Ratios - with our unique admission/eviction policy pairing, Ristretto's performance is best in class.
Eviction: SampledLFU - on par with exact LRU and better performance on Search and Database traces.
Admission: TinyLFU - extra performance with little memory overhead (12 bits per counter).

**Comment by jimisaacs** [comment]
My implementation assumes a stateless container, so I still using your standard local fs, and just make the assumption that what ever is in the cache is the source of truth. Though even if it's not in a stateless container, I'd still almost like to just assume it is, and clear the local storage directory on server start 🤷

**Comment by jimisaacs** [comment]
What is in the cache is just a struct with the name and modtime.

**Comment by ije** [comment]
@jimisaacs there are two different kind of LRUs i think, one is a FS storage that can remove the old(cold) files automatically since the build outputs take lot of storage space over time. the other one is a redis layer to map the request url to the entry JS, currently i only use the `postdb`(a embed db i created) to cache package versions.
